package com.myspace.pet_rule;




/**
 * This class was automatically generated by the data modeler tool.
 */

public class RulesParams implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Number of Claims")
	private java.lang.Integer numberOfClaims;
	@org.kie.api.definition.type.Label("Claims Paid")
	private java.lang.Integer claimsPaid;
	@org.kie.api.definition.type.Label("Pet Neuter")
	private java.lang.Boolean neuter;
	@org.kie.api.definition.type.Label("Factor")
	private java.lang.Double factor;
	@org.kie.api.definition.type.Label("Rating Factor")
	private java.lang.Double ratingFactor;

	@org.kie.api.definition.type.Label("Tier")
	private java.lang.String tier;

	@org.kie.api.definition.type.Label("Modified Rating Factor")
	private Double modifiedRatingFactor;

	public RulesParams() {
	}

	public java.lang.Integer getNumberOfClaims() {
		return this.numberOfClaims;
	}

	public void setNumberOfClaims(java.lang.Integer numberOfClaims) {
		this.numberOfClaims = numberOfClaims;
	}

	public java.lang.Integer getClaimsPaid() {
		return this.claimsPaid;
	}

	public void setClaimsPaid(java.lang.Integer claimsPaid) {
		this.claimsPaid = claimsPaid;
	}

	public java.lang.Boolean getNeuter() {
		return this.neuter;
	}

	public void setNeuter(java.lang.Boolean neuter) {
		this.neuter = neuter;
	}

	public java.lang.Double getFactor() {
		return this.factor;
	}

	public void setFactor(java.lang.Double factor) {
	    String s = String.format("%.4f", factor);
        double value = Double.parseDouble(s);
	    System.out.println("*******"+value+"***********************");
		this.factor = factor;
	}

	public java.lang.Double getRatingFactor() {
		return this.ratingFactor;
	}

	public void setRatingFactor(java.lang.Double ratingFactor) {
		this.ratingFactor = ratingFactor;
	}

	public java.lang.String getTier() {
		return this.tier;
	}

	public void setTier(java.lang.String tier) {
	   
		this.tier = tier;
	}

	public java.lang.Double getModifiedRatingFactor() {
		return this.modifiedRatingFactor;
	}

	public void setModifiedRatingFactor(java.lang.Double modifiedRatingFactor) {
		this.modifiedRatingFactor = modifiedRatingFactor;
	}

	public RulesParams(java.lang.Integer numberOfClaims,
			java.lang.Integer claimsPaid, java.lang.Boolean neuter,
			java.lang.Double factor, java.lang.Double ratingFactor,
			java.lang.String tier, java.lang.Double modifiedRatingFactor) {
		this.numberOfClaims = numberOfClaims;
		this.claimsPaid = claimsPaid;
		this.neuter = neuter;
		this.factor = factor;
		this.ratingFactor = ratingFactor;
		this.tier = tier;
		this.modifiedRatingFactor = modifiedRatingFactor;
	}

}